
/*
 Interview Querstion:
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence up to a given value, find the sum of the even-valued terms
 and the sum of all odd valued terms.
 */
package interviewQuestion;

public class Main {

    public static void main(String[] args) {

        new Program().run(args);

    }

}
