/*
 Interview Question:
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence up to a given value, find the sum of the even-valued terms.
 */

package com.kturley;

import org.jboss.weld.environment.se.Weld;
import org.jboss.weld.environment.se.WeldContainer;

import javax.inject.Singleton;

@Singleton
public class Main {


    public static void main(String[] args) {

//        new Fibber().run(args);

        Weld weld = new Weld();
        WeldContainer container = weld.initialize();
        Fibber application = container.instance().select(Fibber.class).get();
        application.run(args);
        weld.shutdown();

    }

}
