/*
fibonacciUnitTested

By Kyle Turley
kyle@kturley.com

a solution to this interview question:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
Report calculation time in milliseconds.
 */

package com.kturley;

import org.jboss.weld.environment.se.Weld;

public class Main {
    public static void main(String[] args) {
        Weld weld = new Weld();
        weld.initialize().instance().select(Fibber.class).get().run(args);
        weld.shutdown();
    }
}
